# Generated by Django 5.2.4 on 2025-10-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_link",
            field=models.TextField(
                blank=True, null=True, verbose_name="Ссылка для оплаты"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_price_id",
            field=models.TextField(
                blank=True, null=True, verbose_name="ID цены в Stripe"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_session_id",
            field=models.TextField(
                blank=True, null=True, verbose_name="ID сессии Stripe"
            ),
        ),
    ]
